export const countries = [ 
    'Afeganistão',
    'Albânia',
    'Alemanha',
    'Andorra',
    'Angola',
    'Antígua e Barbuda',
    'Arábia Saudita',
    'Argélia',
    'Argentina',
    'Armênia',
    'Austrália',
    'Áustria',
    'Azerbaijão',
    'Bahamas',
    'Bangladexe (Bengala)',
    'Barbados',
    'Barém',
    'Bélgica',
    'Belize',
    'Benim',
    'Bielorrússia (Belarus)',
    'Bolívia',
    'Bósnia e Herzegovina',
    'Botsuana',
    'Brasil',
    'Brunei',
    'Bulgária',
    'Burquina Faso',
    'Burundi',
    'Butão',
    'Cabo Verde',
    'Camarões',
    'Camboja',
    'Canadá',
    'Catar',
    'Cazaquistão',
    'Chade',
    'Chile',
    'China',
    'Chipre',
    'Cingapura',
    'Colômbia',
    'Comores',
    'Congo-Brazzaville (República do Congo)',
    'Congo-Kinshasa (República Democrática do Congo)',
    'Coreia do Norte',
    'Coreia do Sul',
    'Costa do Marfim',
    'Costa Rica',
    'Croácia',
    'Cuba',
    'Dinamarca',
    'Djibouti',
    'Dominica',
    'Egito',
    'Emirados Árabes Unidos',
    'Equador',
    'Eritreia',
    'Eslováquia',
    'Eslovênia',
    'Espanha',
    'Estados Unidos',
    'Estônia',
    'Eswatini',
    'Etiópia',
    'Fiji',
    'Filipinas',
    'Finlândia',
    'França',
    'Gabão',
    'Gâmbia',
    'Gana',
    'Geórgia',
    'Granada',
    'Grécia',
    'Guatemala',
    'Guiana',
    'Guiné',
    'Guiné Equatorial',
    'Guiné-Bissau',
    'Haiti',
    'Holanda (Países Baixos)',
    'Honduras',
    'Hungria',
    'Iémen',
    'Ilhas Marshall',
    'Ilhas Salomão',
    'Índia',
    'Indonésia',
    'Irã',
    'Iraque',
    'Irlanda',
    'Islândia',
    'Israel',
    'Itália',
    'Jamaica',
    'Japão',
    'Jordânia',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Laos',
    'Lesoto',
    'Letônia',
    'Líbano',
    'Libéria',
    'Líbia',
    'Liechtenstein',
    'Lituânia',
    'Luxemburgo',
    'Madagascar',
    'Malásia',
    'Malaui',
    'Maldivas',
    'Mali',
    'Malta',
    'Marrocos',
    'Maurício',
    'Mauritânia',
    'México',
    'Micronésia',
    'Moçambique',
    'Moldávia',
    'Mônaco',
    'Mongólia',
    'Montenegro',
    'Myanmar (Birmânia)',
    'Namíbia',
    'Nauru',
    'Nepal',
    'Nicarágua',
    'Níger',
    'Nigéria',
    'Niue',
    'Noruega',
    'Nova Zelândia',
    'Omã',
    'Palau',
    'Panamá',
    'Papua-Nova Guiné',
    'Paquistão',
    'Paraguai',
    'Peru',
    'Polônia',
    'Portugal',
    'Quênia',
    'Quirguistão',
    'Quiribati',
    'Reino Unido',
    'República Centro-Africana',
    'República Checa',
    'República Dominicana',
    'Romênia',
    'Ruanda',
    'Rússia',
    'Saara Ocidental',
    'Samoa',
    'San Marino',
    'Santa Lúcia',
    'São Cristóvão e Névis',
    'São Tomé e Príncipe',
    'São Vicente e Granadinas',
    'Seicheles',
    'Senegal',
    'Serra Leoa',
    'Sérvia',
    'Singapura',
    'Síria',
    'Somália',
    'Sri Lanka',
    'Suazilândia',
    'Sudão',
    'Sudão do Sul',
    'Suécia',
    'Suíça',
    'Suriname',
    'Tailândia',
    'Taiwan',
    'Tajiquistão',
    'Tanzânia',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad e Tobago',
    'Tunísia',
    'Turcomenistão',
    'Turquia',
    'Tuvalu',
    'Ucrânia',
    'Uganda',
    'Uruguai',
    'Uzbequistão',
    'Vanuatu',
    'Vaticano',
    'Venezuela',
    'Vietnã',
    'Zâmbia',
    'Zimbábue',
];